export const SET_MESSAGE = 'SET_MESSAGE'
export const SET_MESSAGES = 'SET_MESSAGES'
export const SET_CONVERSATION = 'SET_CONVERSATION'
export const SET_CREATE_CONVERSATION = 'SET_CREATE_CONVERSATION'
