version: '3.8'
services:
  test_app:
    image: node:14-alpine3.10
    working_dir: /var/app
    restart: always
    ports:
      - '3000:3000'
    environment:
      - NUXT_HOST=0.0.0.0
      - NUXT_PORT=3000
      - HOST=0.0.0.0
    volumes:
      - ./:/var/app:cached
      # - test_app_sync:/var/app/:nocopy
    command: yarn dev
# volumes:
#   test_app_sync:
#     external: true
